### PR TITLE
Allow to draw grid charts when multiple series of data are given

### PR DESCRIPTION
**Pull request by yutannihilation**
You know, MetricsGraphics.js has a nice feature, linked charts. I found this may be useful to implement `ggplot2`'s `facet_grid`-like chart.

An example is here:
http://rpubs.com/yutannihilation/metricsgraphics_grid

### CODE REVIEW

**Comment by pssguy** [comment]
Nice addition

**Comment by hrbrmstr** [comment]
very nice! let me poke at it a bit, but i should be able to accept the PR w/o changes (given that this is a very new package and subject to change).

**Comment by hrbrmstr** [comment]
Additional note, the current implementation I have does support linked charts - http://rpubs.com/hrbrmstr/52765 - but i don't think this changes that (folks may want separately linked charts for some reason)

**Comment by timelyportfolio** [comment]
Just installed and tested the fancy new `grid` functionality.  Love the concept, but doesn't quite work for me.  If you look closely, the dot follower does not track the line.  I'll research further.

image

**Comment by timelyportfolio** [comment]
Might be a namespace-type issue.  Consider this other flaw.

```
library(metricsgraphics)
library(htmltools)

set.seed(1492)
 stocks <- data.frame(
   time = as.Date('2009-01-01') + 0:9,
   X = rnorm(10, 0, 1),
   Y = rnorm(10, 0, 2),
   Z = rnorm(10, 0, 4))

 stocks %>%
   mjs_plot(x=time, y=X) %>%
   mjs_line() %>%
   mjs_add_line(Y) %>%
   mjs_add_line(Z) %>%
   mjs_axis_x(xax_format="date") %>%
   mjs_add_legend(legend=c("X", "Y", "Z")) %>%
   mjs_grid() -> s1

stocks %>%
  mjs_plot(x=time, y=X) %>%
  mjs_line() %>%
  mjs_add_line(Y) %>%
  mjs_add_line(Z) %>%
  mjs_axis_x(xax_format="date") %>%
  mjs_add_legend(legend=c("X", "Y", "Z")) %>%
  mjs_grid() -> s2

tagList(s1,s2) %>% html_print
```

**Comment by hrbrmstr** [comment]
that's definitely an interesting issue (but, also kinda weird since there
should be unique div's for each).

Also, I need to check with the metricsgraphics docs, but I don't think they
ever expected to have any more than 2 charts linked at the same time. (I
just realized that)

**Comment by timelyportfolio** [comment]
Issue for the `tagList` error is `id` without namespace can only be used once in a page, so at [line 189](https://github.com/hrbrmstr/metricsgraphics/blob/master/inst/htmlwidgets/metricsgraphics.js#L189) duplication is likely.

**Comment by timelyportfolio** [comment]
Even with just `X` and `Y` drawn I get the tooltip dot in the wrong place.

image

**Comment by timelyportfolio** [comment]
As this gets resolved, I would suggest isolating in a branch and reverting `master` back.

**Comment by hrbrmstr** [comment]
aye. agreed. just did it.

**Comment by yutannihilation** [comment]
Thank you for the discussion, and sorry that I didn't notice this bug... I will resolve this and send PR again.

**Comment by yutannihilation** [comment]
I got it!

The problem was that I reused `mg_params` for each chart, so that the side-effects stormed the other charts drawn before. (That's why only the chart drawn last worked fine.) Sorry for my poor Javascript skill...

The fix commit: https://github.com/yutannihilation/metricsgraphics/commit/a2266ed8a37d9c6d26e1b72f3c5ad421b115c326
Proof: http://rpubs.com/yutannihilation/53408

While in official `linked` links two charts (thanks @hrbrmstr for confirming in mozilla/metrics-graphics#309), it seems working with more than two charts. But I'm not sure if we can stably use this feature.

**Comment by yutannihilation** [comment]
What I'm thinking now is whether I should use `$.extend()` or not, since MetricsGraphics.js is leaving from jquery (https://github.com/mozilla/metrics-graphics/pull/267).

**Pull request merged**
