### PR TITLE
added link to an example I made

### PR DESCRIPTION
**Pull request by DocOfi**
Hi,
I thoroughly enjoyed working with your package and created a short presentation/example which can be viewed by clicking on the link in the README.md file.  I hope you like it and include it in your repository.
regards,
Edmund

### CODE REVIEW

**Comment by hrbrmstr** [comment]
O.M.Gosh. This is _amazing_!! Thank you!

Would you mind if I added you as a contributor and worked that example into a Vignette? (You are also welcome to do those things but I feel bad asking you to do more than you already have given the amount of thought, time and effort you've put into it!)

If you are OK with ^^, just drop a comment here with how you'd like your entry to appear in the DESCRIPTION.

**Comment by DocOfi** [comment]
Thanks for the kind comments. I'm relatively new in R.  Been learning it from Coursera.  If you don't mind taking in a newbie who'll probably learn more than he can contribute, I'd like to take your offer.

**Comment by DocOfi** [comment]
BTW, if you think there's something that needs improving in the example I made, please let me know and I'd be happy take care of it.

**Comment by DocOfi** [comment]
I added another example plot at the end. I was planing to include it earlier but somehow got put off. I suddenly remembered it and I couldn't concentrate on my lessons in Coursera until I finished it.  Same link in Rpubs and files in Github have been updated.  Thanks again.

**Pull request merged**
