### PR TITLE
dynamic sizing/resizing behavior

### PR DESCRIPTION
**Pull request by jjallaire**
This set of changes implements automatic sizing/resizing for metrics graphics widgets. This means that they will always size themselves to the dimensions of their container (e.g. the Viewer pane in RStudio, a standalone browser window, the correct knitr figure size, or the size allocated by metricsgraphicsOutput in Shiny). This is preferable to a hard-coded approach because it removes the burden from the user of writing code to get the size just right for whatever context they are using the widget in (note that users can *always* pass an explicit width and height to override this behavior). The article on widget sizing is worth a read for additional context: http://www.htmlwidgets.org/develop_sizing.html

Note that one related change is the elimination of the title and description attributes. The problem they cause for metricsgraphics is that they aren't factored into the size of the graph, so when you pass width and height of the container (e.g. knitr figure size) the space allocated to the title is **in addition to** the graph (so the bottom of the graph is clipped off). This could probably be overcome by doing some dynamic DOM text measurement but that's pretty hairy so not attempted here. My view is that the convenience of automatic sizing outweighs the nicety of having a title (and there are other ways to get titles commonly used such as text headers in Rmd or Shiny, slide headers in presentations, etc.)

### CODE REVIEW

**Comment by timelyportfolio** [comment]
@ramnathv just wanted to make sure you saw this;  know you had initially sketched out a `metrics` widget, and also know `metrics` has changed quite a bit since then

**Comment by hrbrmstr** [comment]
I think I'd have to agree on this (esp as for use in an R context). The mozilla folks definitely seem to have planned for these charts to be in a Bootstrap context (which makes the layout easier and does the description on hover as y'all prbly know already). As an aside, i noticed that knitting an Rmd with (at least these charts) shows up fine in the RStudio viewer, Safari & Firefox, but Chrome tosses errors. Do you see that with any of the other `htmlwidgets`?

**Comment by timelyportfolio** [comment]
The `Bootstrap` and `jquery` dependencies are being discussed (without resolution as far as I can tell) here in this issue https://github.com/mozilla/metrics-graphics/issues/132.

**Comment by jjallaire** [comment]
The chrome issue was due to using a non-minified version of ds.js. I've updated to prevent this.

**Comment by jjallaire** [comment]
There is a merge conflict introduced by a recent commit, I'll resolve this and let you know when things are good to go

**Comment by hrbrmstr** [comment]
You, sir, are a _machine_. I was thinking it might be the unminified js libs. Thx again. I'll hopefully be wrapping a few other libs we use a bit at work.

**Comment by jjallaire** [comment]
Okay, I've fixed the merge conflicts so should be good to go

**Pull request merged**
